title: rosecurity@dev
email: michael@rosesecurity.dev
description: >-
  I build tools that make managing infrastructure easier to run and safer to scale. Day-to-day Iâ€™m in the Terraform and Go trenches, maintaining widely used modules, authoring providers, and contributing to Terraform Best Practices and Terraform Proverbs. Beyond infrastructure, I architect data engineering pipelines and specialize in building scalable ML/AI platforms for companies in the cloud. I live in the CLI, am the creator of Red-Teaming TTPs, and am a MITRE, OWASP, and Debian contributor!

  If you enjoy my community code, blogs, or tools, feel free to reach out and connect!

baseurl: ""
url: "https://rosesecurity.dev"
github_username: RoseSecurity

# build settings
theme: jekyll-dash
plugins:
  - jekyll-feed

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# jekyll tagging
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

include: [CNAME]

dash:
  date_format: "%b %-d, %Y"

  # animation speed of the post scroll-in effect
  animation_speed: 50

  # enable Right-to-Left support or not
  rtl: false

  # replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: RoseSecurity

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
  - url: https://stackoverflow.com/users/22638505
    icon: stack-overflow
    color: orange
  - url: https://github.com/RoseSecurity
    icon: github-square
    color: purple
  - url: mailto:michael@rosesecurity.dev
    icon: envelope
    color: teal

  # author box should be displayed or not
  show_author: true
